export const actionTypes = {
  SAVE_USER: "SAVE_USER",
  SAVE_USER_LIST: "SAVE_USER_LIST",
  SAVE_USER_DETAIL: "SAVE_USER_DETAIL",

  SAVE_MOVIE_LIST: "SAVE_MOVIE_LIST",
  SAVE_MOVIE_DETAIL: "SAVE_MOVIE_DETAIL",

  SAVE_CINEMA_SYSTEM_LIST: "SAVE_CINEMA_SYSTEM_LIST",
  SAVE_CINEMA_SYSTEM_DETAIL: "SAVE_CINEMA_SYSTEM_DETAIL",

  SAVE_CINEMA_LIST: "SAVE_CINEMA_LIST",
  SAVE_CINEMA_DETAIL: "SAVE_CINEMA_DETAIL",

  SAVE_CINEMA_ROOM_LIST: "SAVE_CINEMA_ROOM_LIST",
  SAVE_CINEMA_ROOM_DETAIL: "SAVE_CINEMA_ROOM_DETAIL",

  SAVE_SHOWTIME_LIST: "SAVE_SHOWTIME_LIST",
  SAVE_SHOWTIME_DETAIL: "SAVE_SHOWTIME_DETAIL",

  SAVE_SEAT_LIST: "SAVE_SEAT_LIST",
  SAVE_SEAT_DETAIL: "SAVE_SEAT_DETAIL",

  SAVE_TICKET_LIST: "SAVE_TICKET_LIST",
  SAVE_TICKET_DETAIL: "SAVE_TICKET_DETAIL",
};
