export const sagaTypes = {
  // User
  SIGN_IN_SAGA: "SIGN_IN_SAGA",
  GET_USER_LOGIN_SAGA: "GET_USER_LOGIN_SAGA",
  GET_USER_LIST_SAGA: "SAVE_USER_LIST_SAGA",
  GET_USER_DETAIL_SAGA: "SAVE_USER_DETAIL_SAGA",
  CREATE_USER_SAGA: "CREATE_USER_SAGA",
  UPDATE_USER_SAGA: "UPDATE_USER_SAGA",
  DELETE_USER_SAGA: "DELETE_USER_SAGA",
  UPDATE_USER_PASSWORD_SAGA: "UPDATE_PASSWORD_SAGA",
  UPDATE_USER_AVATAR_SAGA: "UPDATE_USER_AVATAR_SAGA",

  // MOVIE
  GET_MOVIE_LIST_SAGA: "GET_MOVIE_LIST_SAGA",
  GET_MOVIE_DETAIL_SAGA: "GET_MOVIE_DETAIL_SAGA",
  CREATE_MOVIE_SAGA: "CREATE_MOVIE_SAGA",
  UPDATE_MOVIE_SAGA: "UPDATE_MOVIE_SAGA",
  DELETE_MOVIE_SAGA: "DELETE_MOVIE_SAGA",
  UPDATE_MOVIE_POSTER_SAGA: "UPDATE_MOVIE_POSTER_SAGA",

  // CINEMA SYSTEM
  GET_CINEMA_SYSTEM_LIST_SAGA: "GET_CINEMA_SYSTEM_LIST_SAGA",
  GET_CINEMA_SYSTEM_DETAIL_SAGA: "GET_CINEMA_SYSTEM_DETAIL_SAGA",
  CREATE_CINEMA_SYSTEM_SAGA: "CREATE_CINEMA_SYSTEM_SAGA",
  UPDATE_CINEMA_SYSTEM_SAGA: "UPDATE_CINEMA_SYSTEM_SAGA",
  DELETE_CINEMA_SYSTEM_SAGA: "DELETE_CINEMA_SYSTEM_SAGA",
  UPDATE_CINEMA_SYSTEM_LOGO_SAGA: "UPDATE_CINEMA_SYSTEM_LOGO_SAGA",

  // CINEMA
  GET_CINEMA_LIST_SAGA: "GET_CINEMA_LIST_SAGA",
  GET_CINEMA_DETAIL_SAGA: "GET_CINEMA_DETAIL_SAGA",
  CREATE_CINEMA_SAGA: "CREATE_CINEMA_SAGA",
  UPDATE_CINEMA_SAGA: "UPDATE_CINEMA_SAGA",
  DELETE_CINEMA_SAGA: "DELETE_CINEMA_SAGA",
  UPDATE_CINEMA_IMAGE_SAGA: "UPDATE_CINEMA_IMAGE_SAGA",

  // CINEMA_ROOM
  GET_CINEMA_ROOM_LIST_SAGA: "GET_CINEMA_ROOM_LIST_SAGA",
  GET_CINEMA_ROOM_DETAIL_SAGA: "GET_CINEMA_ROOM_DETAIL_SAGA",
  CREATE_CINEMA_ROOM_SAGA: "CREATE_CINEMA_ROOM_SAGA",
  UPDATE_CINEMA_ROOM_SAGA: "UPDATE_CINEMA_ROOM_SAGA",
  DELETE_CINEMA_ROOM_SAGA: "DELETE_CINEMA_ROOM_SAGA",

  // SHOWTIME
  GET_SHOWTIME_LIST_SAGA: "GET_SHOWTIME_LIST_SAGA",
  GET_SHOWTIME_DETAIL_SAGA: "GET_SHOWTIME_DETAIL_SAGA",
  CREATE_SHOWTIME_SAGA: "CREATE_SHOWTIME_SAGA",
  UPDATE_SHOWTIME_SAGA: "UPDATE_SHOWTIME_SAGA",
  DELETE_SHOWTIME_SAGA: "DELETE_SHOWTIME_SAGA",

  // SEAT
  GET_SEAT_LIST_SAGA: "GET_SEAT_LIST_SAGA",
  GET_SEAT_LIST_BY_SHOWTIME_SAGA: "GET_SEAT_LIST_BY_SHOWTIME_SAGA",
  GET_SEAT_DETAIL_SAGA: "GET_SEAT_DETAIL_SAGA",
  CREATE_SEAT_SAGA: "CREATE_SEAT_SAGA",
  UPDATE_SEAT_SAGA: "UPDATE_SEAT_SAGA",
  DELETE_SEAT_SAGA: "DELETE_SEAT_SAGA",
  CREATE_MULTIPLE_SEATS_SAGA: "CREATE_MULTIPLE_SEATS_SAGA",

  // TICKET
  GET_TICKET_LIST_SAGA: "GET_TICKET_LIST_SAGA",
  GET_TICKET_DETAIL_SAGA: "GET_TICKET_DETAIL_SAGA",
  CREATE_TICKET_SAGA: "CREATE_TICKET_SAGA",
  UPDATE_TICKET_SAGA: "UPDATE_TICKET_SAGA",
  DELETE_TICKET_SAGA: "DELETE_TICKET_SAGA",
};
